In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
import pandas as pd

path = "retraite_actifs_cotisants_2012-2024.xlsx"

df = pd.read_excel(
    path,
    engine="openpyxl"
)

print("Dimensions :", df.shape)

display(df.head())

Dimensions : (5, 14)

,Unnamed: 0,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Régimes de base,3512908,3662049.0,3790771.0,3885081.0,4047903.0,4170369.0,4270358.0,4358631.0,4127129.0,4417696.0,4656174.0,4827189.0,4935200.0
1,Régimes complémentaires,315574,322596.0,335776.0,340821.0,355150.0,366070.0,379076.0,396911.0,401002.0,417177.0,439346.0,460233.0,478623.0
2,Total,3828482,3984645.0,4126547.0,4225902.0,4403053.0,4536439.0,4649434.0,4755542.0,4528131.0,4834873.0,5095520.0,5287422.0,5413823.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Evolution des actifs cotisants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print("Colonnes :")
print(df.columns.tolist())

Colonnes :
['Unnamed: 0', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  3 non-null      str
 1   2012        4 non-null      object
 2   2013        3 non-null      float64
 3   2014        3 non-null      float64
 4   2015        3 non-null      float64
 5   2016        3 non-null      float64
 6   2017        3 non-null      float64
 7   2018        3 non-null      float64
 8   2019        3 non-null      float64
 9   2020        3 non-null      float64
 10  2021        3 non-null      float64
 11  2022        3 non-null      float64
 12  2023        3 non-null      float64
 13  2024        3 non-null      float64
dtypes: float64(12), object(1), str(1)
memory usage: 692.0+ bytes

In [5]:
df.isna().sum()

Unnamed: 0    2
2012          1
2013          2
2014          2
2015          2
2016          2
2017          2
2018          2
2019          2
2020          2
2021          2
2022          2
2023          2
2024          2
dtype: int64

In [6]:
import pandas as pd
import numpy as np

# 1. Lire le fichier
path = "retraite_actifs_cotisants_2012-2024.xlsx"

df = pd.read_excel(
    path,
    engine="openpyxl"
)

# 2. Renommer la première colonne
df = df.rename(columns={"Unnamed: 0": "regime"})

# 3. Supprimer les lignes complètement vides
df = df.dropna(how="all")

# 4. Supprimer les lignes qui ne contiennent pas de données
df = df[
    df["regime"].isin([
        "Régimes de base",
        "Régimes complémentaires",
        "Total"
    ])
]

# 5. Transformer les années en lignes
df_long = df.melt(
    id_vars="regime",
    var_name="annee",
    value_name="actifs_cotisants"
)

# 6. Convertir les années en entier
df_long["annee"] = df_long["annee"].astype(int)

# 7. Convertir les actifs cotisants en numérique
df_long["actifs_cotisants"] = pd.to_numeric(
    df_long["actifs_cotisants"],
    errors="coerce"
)

# 8. Trier les données
df_long = df_long.sort_values(
    ["annee", "regime"]
).reset_index(drop=True)

# Afficher le résultat
display(df_long)

                     regime  annee  actifs_cotisants
0   Régimes complémentaires   2012            315574
1           Régimes de base   2012           3512908
2                     Total   2012           3828482
3   Régimes complémentaires   2013            322596
4           Régimes de base   2013           3662049
5                     Total   2013           3984645
6   Régimes complémentaires   2014            335776
7           Régimes de base   2014           3790771
8                     Total   2014           4126547
9   Régimes complémentaires   2015            340821
10          Régimes de base   2015           3885081
11                    Total   2015           4225902
12  Régimes complémentaires   2016            355150
13          Régimes de base   2016           4047903
14                    Total   2016           4403053
15  Régimes complémentaires   2017            366070
16          Régimes de base   2017           4170369
17                    Total   2017           4536439
18  Régimes complémentaires   2018            379076
19          Régimes de base   2018           4270358
20                    Total   2018           4649434
21  Régimes complémentaires   2019            396911
22          Régimes de base   2019           4358631
23                    Total   2019           4755542
24  Régimes complémentaires   2020            401002
25          Régimes de base   2020           4127129
26                    Total   2020           4528131
27  Régimes complémentaires   2021            417177
28          Régimes de base   2021           4417696
29                    Total   2021           4834873
30  Régimes complémentaires   2022            439346
31          Régimes de base   2022           4656174
32                    Total   2022           5095520
33  Régimes complémentaires   2023            460233
34          Régimes de base   2023           4827189
35                    Total   2023           5287422
36  Régimes complémentaires   2024            478623
37          Régimes de base   2024           4935200
38                    Total   2024           5413823

In [7]:
print("Dimensions :", df_long.shape)

print("\nInformations :")
df_long.info()

print("\nValeurs manquantes :")
print(df_long.isna().sum())

Dimensions : (39, 3)

Informations :
<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   regime            39 non-null     str
 1   annee             39 non-null     int64
 2   actifs_cotisants  39 non-null     int64
dtypes: int64(2), str(1)
memory usage: 1.0 KB

Valeurs manquantes :
regime              0
annee               0
actifs_cotisants    0
dtype: int64

In [9]:
df_long.to_csv(
    "actifs_cotisants_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

print("✅ Fichier nettoyé enregistré avec succès")

✅ Fichier nettoyé enregistré avec succès

In [2]:
# 1. Vérifier la structure
print(actifs_cotisants_clean.shape)
print(actifs_cotisants_clean.columns.tolist())

# 2. Vérifier les valeurs manquantes
print(actifs_cotisants_clean.isna().sum())

# 3. Vérifier les doublons
print("Doublons :", actifs_cotisants_clean.duplicated().sum())

# 4. Vérifier l'unicité année + régime
print(
    "Doublons année-régime :",
    actifs_cotisants_clean.duplicated(
        subset=["annee", "regime"]
    ).sum()
)

# 5. Vérifier les années et les régimes
print(sorted(actifs_cotisants_clean["annee"].unique()))
print(actifs_cotisants_clean["regime"].unique())

NameError: name 'actifs_cotisants_clean' is not defined