In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
import pandas as pd

path = "retraite_beneficiaires_2012-2024.xlsx"

df = pd.read_excel(
    path,
    engine="openpyxl"
)

print("Dimensions :", df.shape)

display(df.head())

Dimensions : (12, 14)

,Unnamed: 0,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,RETRAITES,635904,668702.0,713182.0,760217.0,808855.0,851116.0,900862.0,939066.0,986589.0,1035037.0,1082372.0,1133023.0,1186948.0
1,Régimes de base,533938,560868.0,600707.0,642741.0,686408.0,722878.0,768081.0,800912.0,843536.0,887308.0,929703.0,975000.0,1023753.0
2,Régimes complémentaires,101966,107834.0,112475.0,117476.0,122447.0,128238.0,132781.0,138154.0,143053.0,147729.0,152669.0,158023.0,163195.0
3,CONJOINTS,289099,295513.0,307580.0,312080.0,319366.0,338876.0,346754.0,361394.0,388112.0,407081.0,411710.0,432309.0,443169.0
4,Régimes de base,245628,251353.0,264763.0,267781.0,273627.0,291506.0,298883.0,312108.0,337008.0,353538.0,356698.0,376027.0,387098.0

In [3]:
print("Colonnes :")
print(df.columns.tolist())

Colonnes :
['Unnamed: 0', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10 non-null     str
 1   2012        11 non-null     object
 2   2013        10 non-null     float64
 3   2014        10 non-null     float64
 4   2015        10 non-null     float64
 5   2016        10 non-null     float64
 6   2017        10 non-null     float64
 7   2018        10 non-null     float64
 8   2019        10 non-null     float64
 9   2020        10 non-null     float64
 10  2021        10 non-null     float64
 11  2022        10 non-null     float64
 12  2023        10 non-null     float64
 13  2024        10 non-null     float64
dtypes: float64(12), object(1), str(1)
memory usage: 1.4+ KB

In [5]:
df.isna().sum()

Unnamed: 0    2
2012          1
2013          2
2014          2
2015          2
2016          2
2017          2
2018          2
2019          2
2020          2
2021          2
2022          2
2023          2
2024          2
dtype: int64

In [7]:
import pandas as pd
import numpy as np

# 1. Lire le fichier
path = "retraite_beneficiaires_2012-2024.xlsx"

df = pd.read_excel(
    path,
    engine="openpyxl"
)

# 2. Renommer la première colonne
df = df.rename(columns={"Unnamed: 0": "regime"})

# 3. Supprimer les lignes complètement vides
df = df.dropna(how="all")

# 4. Supprimer les lignes qui ne contiennent pas de données
df = df[
    df["regime"].isin([
        "Régimes de base",
        "Régimes complémentaires",
        "Total"
    ])
]

# 5. Transformer les années en lignes
df_long = df.melt(
    id_vars="regime",
    var_name="annee",
    value_name="actifs_cotisants"
)

# 6. Convertir les années en entier
df_long["annee"] = df_long["annee"].astype(int)

# 7. Convertir les actifs cotisants en numérique
df_long["actifs_cotisants"] = pd.to_numeric(
    df_long["actifs_cotisants"],
    errors="coerce"
)

# 8. Trier les données
df_long = df_long.sort_values(
    ["annee", "regime"]
).reset_index(drop=True)

# Afficher le résultat
display(df_long)

                     regime  annee  actifs_cotisants
0   Régimes complémentaires   2012          101966.0
1   Régimes complémentaires   2012           43471.0
2   Régimes complémentaires   2012             391.0
3           Régimes de base   2012          533938.0
4           Régimes de base   2012          245628.0
..                      ...    ...               ...
73  Régimes complémentaires   2024           56071.0
74  Régimes complémentaires   2024            1071.0
75          Régimes de base   2024         1023753.0
76          Régimes de base   2024          387098.0
77          Régimes de base   2024           71826.0

[78 rows x 3 columns]

In [8]:
print("Dimensions :", df_long.shape)

print("\nInformations :")
df_long.info()

print("\nValeurs manquantes :")
print(df_long.isna().sum())

Dimensions : (78, 3)

Informations :
<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   regime            78 non-null     str
 1   annee             78 non-null     int64
 2   actifs_cotisants  78 non-null     float64
dtypes: float64(1), int64(1), str(1)
memory usage: 2.0 KB

Valeurs manquantes :
regime              0
annee               0
actifs_cotisants    0
dtype: int64

In [10]:
df_long.to_csv(
    "retraite_beneficiaires_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

print("✅ Fichier nettoyé enregistré avec succès")

✅ Fichier nettoyé enregistré avec succès